apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: feignuser
  name: feignuser
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: feignuser
    spec:
      containers:
      - image: nocoolming/feign-user:0.0.3
        name: feignuser
        resources: {}
      hostname: feignUser
      restartPolicy: Always
status: {}
